@baseUrl=http://localhost:5000

### Health
GET {{baseUrl}}/health

### Zoho ###

### 01 getModuleRecords
GET {{baseUrl}}/leads

### 02 getRecord
@leadId=846472000000382071
GET {{baseUrl}}/leads/{{leadId}}

### 03 Create Lead
POST {{baseUrl}}/leads
Content-Type: application/json

{
  "FIRST_NAME": "praveen12",
  "LAST_NAME":"ande12",
  "EMAIL":"praveenande12@example.com"
}

### 04 Update Lead
@leadId=846472000000383005
PUT {{baseUrl}}/leads/{{leadId}}
Content-Type: application/json

{
  "FIRST_NAME": "updated praveen12",
  "LAST_NAME":"updated ande12",
  "EMAIL":"updatedpraveenande12@example.com"
}

### 05 Delete Particular Record
@leadId=846472000000389041
DELETE {{baseUrl}}/leads/{{leadId}}
Content-Type: application/json
