@baseUrl=http://localhost:5000

### Health
GET {{baseUrl}}/health

### Zoho ###

### 01 Get All Leads
GET {{baseUrl}}/leads

### 02 Get Particular Lead
@leadId=846472000000374028
GET {{baseUrl}}/leads/{{leadId}}

### Create Lead
POST {{baseUrl}}/leads
Content-Type: application/json

{
  "FIRST_NAME": "praveen1",
  "LAST_NAME":"ande1"
}