@baseUrl=http://localhost:5000

### Health
GET {{baseUrl}}/health

### Zoho ###

### 01 Get All Leads
GET {{baseUrl}}/leads

### 02 Get Particular Lead
@leadId=846472000000357398
GET {{baseUrl}}/leads/{{leadId}}