@baseUrl=http://localhost:5000

### Health
GET {{baseUrl}}/health

### Modules ###

### 01 Get All Modules
GET {{baseUrl}}/modules

### Records ###

### 01 Get All Records
GET {{baseUrl}}/records

### 02 Get a Single Record
@recordId=846472000000438016
GET {{baseUrl}}/records/{{recordId}}

### 03 Create Record
POST {{baseUrl}}/records
Content-Type: application/json

{
  "First_Name":"praveen7",
  "Last_Name": "ande7",
  "Email":"praveenande7@gmail.com"
}

### 04 Update a Record
@updateRecordId=846472000000424101
PUT {{baseUrl}}/records/{{updateRecordId}}
Content-Type: application/json

{
  "First_Name":"updated praveen6",
  "Last_Name": "updated ande6",
  "Email":"updatepraveenande6@gmail.com"
}

### 05 Delete a Record
@deleteRecordId=846472000000438016
DELETE {{baseUrl}}/records/{{deleteRecordId}}